### ISSUE TITLE
Sonos media player support

### ISSUE THREAD

**Issue by spacecakes** [alberti42/Volume-Control#17]
Hi. Not an issue but a question: you think it would be possible to add Sonos support to this app, so that you could pick it among the media players and control volume?

**Comment by shlomiuziel** [comment]
@spacecakes I started working on adding Sonos support, just to discover that the Sonos app isn't scriptable and does not expose any dictionary of scripting suites.
An awkward solution could be to either find such 3rd party Sonos scriptable controller, or make one your own (E.g. a simple Python client that wraps simple playback actions over [https://github.com/SoCo/SoCo](url) and exposes script actions.

**Comment by spacecakes** [comment]
@shlomiuziel thanks for clarifying! Yeah there are other means of controlling it like [SoCo](https://github.com/SoCo/SoCo) and [Menubar Controller for Sonos](https://mbc-for-sonos.app/), which I both use to varying degree, but nothing beats the UX of just turning the volume control using your app.

**Comment by shlomiuziel** [comment]
I agree, I'm saying that if we'll have an alternative Sonos controller that responds to Apple Scripting, we could pretty easily extend Volume Control to use Sonos through that.
