### ISSUE TITLE
Typo in Menubar

### ISSUE THREAD

**Issue by simonnelli** [alberti42/Volume-Control#21]
When selecting 'hide menubar icon' there is a small typo in the popup. It says 'manubar' instead of menubar
<img width="322" alt="Screenshot 2023-04-14 at 17 24 12" src="https://user-images.githubusercontent.com/32964940/232087469-ccbb697f-303b-462e-b78b-a6e5c6737d68.png">

**Comment by alberti42** [comment]
Thank you for spotting the mistake! I will correct it.

**Comment by porg** [comment]
Note: The typo is still present in v1.7.4

**Comment by alberti42** [comment]
It took long time but I finally corrected the typo. You can search for new updates and this should allow you to update the app automatically.

![Bildschirmfoto 2024-10-27 um 17 59 49](https://github.com/user-attachments/assets/bd667dca-2c8e-4cd9-8880-81869e0fb9f0)
