### ISSUE TITLE
How to delete the app?

### ISSUE THREAD

**Issue by JamesB374** [alberti42/Volume-Control#28]
Hey, what's the best way to delete the app? Especially to get rid of the Background music XPC helper account (its nit shown in settings, but I can give it permissions for file (read/write).

**Comment by alberti42** [comment]
What is the background XPC helper account? My app does not install anything of this kind. If you want to remove the app, just drag the app into the trashbin and delete the small file of less than 1 KB located at `<YOUR HOME>/Library/Preferences/org.Alberti42.VolumeControl.plist`.

**Comment by JamesB374** [comment]
Thanks for your quick replay! Your right, im really sorry, I thought your app added the XPC helper account on my Mac, but it was Background music 0.4.0, wich I uninstalled couple month ago in exchange for volume control.
