### ISSUE TITLE
Volume Control won't open under macOS 15.2 (public beta)

### ISSUE THREAD

**Issue by allygill** [alberti42/Volume-Control#30]

**Comment by alberti42** [comment]
Thanks for the feedback. A few other users reported similar problems and were able to fix them by re-signing the application. Can you follow these instructions: https://github.com/alberti42/Volume-Control?tab=readme-ov-file#note_codesign

It would be great if you can give feedback if this works. Then I will write it in the front page what should be done after the update.

If I had known it in advance, I would have communicated in the change log that the application has to be signed again after the update.

**Comment by allygill** [comment]
Yes - the good news is that this worked! But I had already. tried it and it didn’t make any difference so I think the order in which you take the actions might be important!

BR
Ally

**Comment by alberti42** [comment]
Thanks for the feedback!
